//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceEvento.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int Id { get; set; }
        public string Nom_Evento { get; set; }
        public int IdEstado { get; set; }
    }
}
