//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCalendarioRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int Id { get; set; }
        public int IdEvento { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public string HoraInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string HoraFin { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string TituloCita { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual EstadoCita EstadoCita { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
