//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCalendarioRest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_CitasEntities : DbContext
    {
        public DB_CitasEntities()
            : base("name=DB_CitasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<EstadoCita> EstadoCita { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<ConsultaCitaXId_Result> ConsultaCitaXId(Nullable<int> idCita)
        {
            var idCitaParameter = idCita.HasValue ?
                new ObjectParameter("idCita", idCita) :
                new ObjectParameter("idCita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultaCitaXId_Result>("ConsultaCitaXId", idCitaParameter);
        }
    
        public virtual ObjectResult<ConsultarTodasCitas_Result> ConsultarTodasCitas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarTodasCitas_Result>("ConsultarTodasCitas");
        }
    
        public virtual int ActualizarRegistros(Nullable<int> id, Nullable<int> idEstado, Nullable<int> idEvento, Nullable<System.DateTime> fechaInicial, string horaInicial, Nullable<System.DateTime> fechaFin, string horaFinal, string titulo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var idEventoParameter = idEvento.HasValue ?
                new ObjectParameter("idEvento", idEvento) :
                new ObjectParameter("idEvento", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var horaInicialParameter = horaInicial != null ?
                new ObjectParameter("HoraInicial", horaInicial) :
                new ObjectParameter("HoraInicial", typeof(string));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var horaFinalParameter = horaFinal != null ?
                new ObjectParameter("HoraFinal", horaFinal) :
                new ObjectParameter("HoraFinal", typeof(string));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarRegistros", idParameter, idEstadoParameter, idEventoParameter, fechaInicialParameter, horaInicialParameter, fechaFinParameter, horaFinalParameter, tituloParameter);
        }
    
        public virtual ObjectResult<ConsultarEstados_Result> ConsultarEstados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarEstados_Result>("ConsultarEstados");
        }
    
        public virtual ObjectResult<PRC_VALIDAR_AGENDA_CITA_Result> PRC_VALIDAR_AGENDA_CITA(string fECHAI, string hORAI, string fECHAF, string hORAF)
        {
            var fECHAIParameter = fECHAI != null ?
                new ObjectParameter("FECHAI", fECHAI) :
                new ObjectParameter("FECHAI", typeof(string));
    
            var hORAIParameter = hORAI != null ?
                new ObjectParameter("HORAI", hORAI) :
                new ObjectParameter("HORAI", typeof(string));
    
            var fECHAFParameter = fECHAF != null ?
                new ObjectParameter("FECHAF", fECHAF) :
                new ObjectParameter("FECHAF", typeof(string));
    
            var hORAFParameter = hORAF != null ?
                new ObjectParameter("HORAF", hORAF) :
                new ObjectParameter("HORAF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRC_VALIDAR_AGENDA_CITA_Result>("PRC_VALIDAR_AGENDA_CITA", fECHAIParameter, hORAIParameter, fECHAFParameter, hORAFParameter);
        }
    }
}
